In [13]:
from datasets import load_dataset
from glob import glob
from tqdm import tqdm
import numpy as np
import math
from fractions import Fraction
import json
import pandas as pd

In [14]:
def get_vectors(angles):
    return np.column_stack((np.sin(angles*(np.pi/2)),np.cos(angles*(np.pi/2))))

In [15]:
def get_angles(vectors):
    return np.array([math.atan2(*x) / (np.pi / 2)  for x in vectors])

In [16]:
def convertMedienlandschaft(x):
    return float(-Fraction(4/3)+Fraction(1/3)*x)

In [17]:
v_linke = [-1.0, 0.0]
v_gruene = [-0.9077674463309972, 0.4194737934385177]
v_spd = [-0.8074405688999996, 0.5899489195637577]
v_fdp = [0.0, 1.0]
v_cdu = [0.614758038308033, 0.788715762702673]
v_afd = [1.0, 0.0]

In [18]:
a_linke = math.atan2(*v_linke) / (np.pi / 2)
a_gruene = math.atan2(*v_gruene) / (np.pi / 2)
a_spd = math.atan2(*v_spd) / (np.pi / 2)
a_fdp = math.atan2(*v_fdp) / (np.pi / 2)
a_cdu = math.atan2(*v_cdu) / (np.pi / 2)
a_afd = math.atan2(*v_afd) / (np.pi / 2)

In [19]:
initial_angles = np.array([a_linke, a_gruene, a_spd, a_fdp, a_cdu, a_afd])

In [20]:
initial_angles

array([-1.        , -0.72442922, -0.59829574,  0.        ,  0.42149268,
        1.        ])

In [21]:
initial_angles*90

array([-90.        , -65.19862967, -53.84661654,   0.        ,
        37.93434103,  90.        ])

In [22]:
(initial_angles*90)+90

array([  0.        ,  24.80137033,  36.15338346,  90.        ,
       127.93434103, 180.        ])

In [23]:
initial_vectors = np.array([v_linke, v_gruene, v_spd, v_fdp, v_cdu, v_afd])

In [24]:
exp = {}
exp['NLP-UniBW/deutschlandfunk_de_classified'] = convertMedienlandschaft(3.8)
exp['NLP-UniBW/focus_de_classified'] = convertMedienlandschaft(4.9)
exp['NLP-UniBW/linksunten_classified'] = convertMedienlandschaft(2.0)
exp['NLP-UniBW/taz_de_classified'] = convertMedienlandschaft(2.8)
exp['NLP-UniBW/zeit_de_classified'] = convertMedienlandschaft(3.6)
exp['NLP-UniBW/stern_de_classified'] = convertMedienlandschaft(3.8)
exp['NLP-UniBW/tichyseinblick_de_classified'] = convertMedienlandschaft(5.5)
exp['NLP-UniBW/cicero_de_classified'] = convertMedienlandschaft(4.9)
exp['NLP-UniBW/spiegel_de_classified'] = convertMedienlandschaft(3.5)
exp['NLP-UniBW/vice_de_classified'] = convertMedienlandschaft(2.8)
exp['NLP-UniBW/tagesschau_de_classified'] = convertMedienlandschaft(3.7)
exp['NLP-UniBW/sueddeutsche_de_classified'] = convertMedienlandschaft(3.5)
exp['NLP-UniBW/welt_de_classified'] = convertMedienlandschaft(4.8)
exp['NLP-UniBW/mdr_de_classified'] = convertMedienlandschaft(4.1)
exp['NLP-UniBW/der_freitag_de_classified'] = convertMedienlandschaft(2.7)
exp['NLP-UniBW/frankfurter_rundschau_de_classified'] = convertMedienlandschaft(3.4)
exp['NLP-UniBW/bild_de_classified'] = convertMedienlandschaft(5.2)
exp['NLP-UniBW/russia_today_de_classified'] = convertMedienlandschaft(5.1)
exp['NLP-UniBW/tagesspiegel_de_classified'] = convertMedienlandschaft(3.6)
exp['NLP-UniBW/br_de_classified'] = convertMedienlandschaft(4.4)
exp['NLP-UniBW/achgut_de_classified'] = convertMedienlandschaft(5.2)
exp['NLP-UniBW/wdr_de_classified'] = convertMedienlandschaft(3.5)
exp['NLP-UniBW/neues_deutschland_de_classified'] = convertMedienlandschaft(2.6)
exp['NLP-UniBW/compact_de_classified'] = convertMedienlandschaft(6.0)
exp['NLP-UniBW/ndr_de_classified'] = convertMedienlandschaft(3.7)
exp['NLP-UniBW/nachdenkseiten_de_classified'] = convertMedienlandschaft(3.1)
exp['NLP-UniBW/junge_freiheit_de_classified'] = convertMedienlandschaft(5.8)
exp['NLP-UniBW/rtl_de_classified'] = convertMedienlandschaft(4.5)
exp['NLP-UniBW/junge_welt_classified'] = convertMedienlandschaft(2.4)
exp['NLP-UniBW/ntv_de_classified'] = convertMedienlandschaft(4.3)
exp['NLP-UniBW/jungle_world_classified'] = convertMedienlandschaft(2.3)
exp['NLP-UniBW/frankfurter_allgemeine_de_classified'] = convertMedienlandschaft(4.5)
exp['NLP-UniBW/mm_news_de_classified'] = convertMedienlandschaft(5.1)

In [25]:
df = load_dataset("NLP-UniBW/deutschlandfunk_de_classified", split="train").to_pandas()
l_ref = []
l_classifier = []
for x in list(df.keys()):
    ref = x.replace("_", "-").split("-")[0]
    if ref in l_ref:
        l_classifier.append("_".join(x.split("_")[:-1]))
    l_ref.append(ref)
l_classifier = sorted(list(set(l_classifier)))
l_parties = ['DIE LINKE', 'BÜNDNIS 90/DIE GRÜNEN', 'SPD', 'FDP', 'CDU/CSU', 'AfD']

l_newspapers = [
    'NLP-UniBW/deutschlandfunk_de_classified',
    'NLP-UniBW/focus_de_classified',
    'NLP-UniBW/linksunten_classified',
    'NLP-UniBW/taz_de_classified',
    'NLP-UniBW/zeit_de_classified',
    'NLP-UniBW/stern_de_classified',
    'NLP-UniBW/tichyseinblick_de_classified',
    'NLP-UniBW/cicero_de_classified',
    'NLP-UniBW/spiegel_de_classified',
    'NLP-UniBW/vice_de_classified',
    'NLP-UniBW/tagesschau_de_classified',
    'NLP-UniBW/sueddeutsche_de_classified',
    'NLP-UniBW/welt_de_classified',
    'NLP-UniBW/mdr_de_classified',
    'NLP-UniBW/der_freitag_de_classified',
    'NLP-UniBW/frankfurter_rundschau_de_classified',
    'NLP-UniBW/bild_de_classified',
    'NLP-UniBW/russia_today_de_classified',
    'NLP-UniBW/tagesspiegel_de_classified',
    'NLP-UniBW/br_de_classified',
    'NLP-UniBW/achgut_de_classified',
    'NLP-UniBW/wdr_de_classified',
    'NLP-UniBW/neues_deutschland_de_classified',
    'NLP-UniBW/compact_de_classified',
    'NLP-UniBW/ndr_de_classified',
    'NLP-UniBW/nachdenkseiten_de_classified',
    'NLP-UniBW/junge_freiheit_de_classified',
    'NLP-UniBW/rtl_de_classified',
    'NLP-UniBW/junge_welt_classified',
    'NLP-UniBW/ntv_de_classified',
    'NLP-UniBW/jungle_world_classified',
    'NLP-UniBW/frankfurter_allgemeine_de_classified',
    'NLP-UniBW/mm_news_de_classified',
]

In [26]:
d_newspapers_df = {}
for newspapers in tqdm(l_newspapers):
    df = load_dataset(newspapers, split="train").to_pandas()
    df = df[df['politic']>=0.8].reset_index(drop=True)
    #df = df.head(1000) #reduce size
    d_newspapers_df[newspapers] = df

100%|██████████| 33/33 [02:30<00:00,  4.57s/it]


In [27]:
d_np = {}
for classifier in l_classifier:
    d_np[classifier] = {}
    for newspaper in l_newspapers:
        df = d_newspapers_df[newspaper][[classifier+"_"+x for x in l_parties]]
        d_np[classifier][newspaper] = np.array(df)

In [37]:
d_mae = {}
d_mse = {}
for classifier in l_classifier:
    mae = 0
    mse = 0
    for newspaper in d_np[classifier]:
        mae = mae + np.abs(np.mean(np.atan2(*(d_np[classifier][newspaper]@initial_vectors).T)/(np.pi/2)) - exp[newspaper])
        mse = mse + np.abs(np.mean(np.atan2(*(d_np[classifier][newspaper]@initial_vectors).T)/(np.pi/2)) - exp[newspaper])**2
    mae = mae/len(l_newspapers)
    mse = mse/len(l_newspapers)
    d_mae[classifier] = float(mae)
    d_mse[classifier] = float(mse)

In [38]:
d_mae

{'DeBERTa-large': 0.19656059345835275,
 'EuroBERT-210m': 0.3041289192928852,
 'EuroBERT-610m': 0.41862818252424017,
 'EuroBERT_2_1B': 0.30501415991828984,
 'GottBERT_large': 0.22537055122256944,
 'Llama-3.2-1B': 0.20881140717620145,
 'Llama-3.2-3B': 0.25048211511034557,
 'gbert-large': 0.19649076208976185,
 'gelectra-large': 0.21118089053004102,
 'gemma-2-2b': 0.18522044495901727,
 'gemma-2-9b': 0.18589730117526596,
 'gemma-3-1b': 0.37088804819812893,
 'xlm-roberta-large': 0.22525084872543893}

In [39]:
d_mae.values()

dict_values([0.19656059345835275, 0.3041289192928852, 0.41862818252424017, 0.30501415991828984, 0.22537055122256944, 0.20881140717620145, 0.25048211511034557, 0.19649076208976185, 0.21118089053004102, 0.18522044495901727, 0.18589730117526596, 0.37088804819812893, 0.22525084872543893])

In [40]:
d_mae.keys()

dict_keys(['DeBERTa-large', 'EuroBERT-210m', 'EuroBERT-610m', 'EuroBERT_2_1B', 'GottBERT_large', 'Llama-3.2-1B', 'Llama-3.2-3B', 'gbert-large', 'gelectra-large', 'gemma-2-2b', 'gemma-2-9b', 'gemma-3-1b', 'xlm-roberta-large'])

In [43]:
df = pd.DataFrame(
    {
        'Classifier':d_mse.keys(),
        'Mean Squared Error':d_mse.values(),
        'Mean Average Error':d_mae.values(),
        'Error in Percent':['{:.2f}'.format((x/2)*100)+"%" for x in d_me.values()]
    }
).sort_values(by=['Mean Squared Error']).reset_index(drop=True)
df

Classifier  Mean Squared Error  Mean Average Error Error in Percent
0          gemma-2-9b            0.046571            0.185897            9.29%
1          gemma-2-2b            0.053105            0.185220            9.26%
2       DeBERTa-large            0.055045            0.196561            9.83%
3        Llama-3.2-1B            0.061169            0.208811           10.44%
4         gbert-large            0.061895            0.196491            9.82%
5      gelectra-large            0.065540            0.211181           10.56%
6      GottBERT_large            0.070863            0.225371           11.27%
7   xlm-roberta-large            0.079544            0.225251           11.26%
8        Llama-3.2-3B            0.087432            0.250482           12.52%
9       EuroBERT-210m            0.143124            0.304129           15.21%
10      EuroBERT_2_1B            0.145841            0.305014           15.25%
11         gemma-3-1b            0.201847            0.370888           18.54%
12      EuroBERT-610m            0.249065            0.418628           20.93%

In [35]:
df.to_json("results_without_optimization.json")